### ISSUE TITLE
Mount Point Size Not Displayed Correctly When Adding NFS Storage

### ISSUE THREAD

**Issue by vigneshvrm** [DIMSI-IS/BackROLL#32]
Hello,

I have an NFS mount at '/mnt/share1/', but when I add the storage, it only shows the server's available space, not the size of the mounted point. I have made the mount persistent using the fstab entry provided below.

I am using the development version
~~~
https://github.com/DIMSI-IS/BackROLL/tree/main/compose_project
~~~

Fstab entry
~~~
10.1.33.11:/backroll /mnt/share1 nfs defaults 0 0
~~~

![Screenshot 2024-08-30 152904](https://github.com/user-attachments/assets/78d49aec-f271-4f7a-816f-39cb7ee3abc2)
![Screenshot 2024-08-30 152750](https://github.com/user-attachments/assets/465cadd9-175c-4191-8f91-0484c9de4b0e)

**Comment by JoffreyLuang** [comment]
Hi Vigneshvrm,

Does it still persist after restarting all the containers?

Regards,

**Comment by vigneshvrm** [comment]
Hi JoffreyLuang,

No after restarting the container the size has been updated but can't take VM backup


~~~
Traceback (most recent call last):
  File "/app/python-env/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/app/python-env/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/app/backup_tasks/single_backup.py", line 161, in single_vm_backup
    raise backup_error
  File "/app/src/app/backup_tasks/single_backup.py", line 154, in single_vm_backup
    raise startbackup_error
  File "/app/src/app/backup_tasks/single_backup.py", line 150, in single_vm_backup
    backup_result = backup_creation(virtual_machine_info)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/app/backup_tasks/single_backup.py", line 137, in backup_creation
    raise sequence_error
  File "/app/src/app/backup_tasks/single_backup.py", line 133, in backup_creation
    return backup_sequence(info, host_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/app/backup_tasks/single_backup.py", line 126, in backup_sequence
    raise backup_error
  File "/app/src/app/backup_tasks/single_backup.py", line 93, in backup_sequence
    backup_job.manage_backing_file(disk)
  File "/app/src/app/borg/borg_core.py", line 155, in manage_backing_file
    qemu_img_info = json.loads(qemu_img_info)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
~~~

**Comment by JoffreyLuang** [comment]
Alright, now the containers have access to your backup storage.
Do the containers have access to your kvm VMs storage? 

To perform backup and restore tasks, Backroll's workers need an access to the VMs storage and to a backup storage.
By default in the docker-compose.yml, /mnt/ is mapped to /mnt/ in the workers.
Please refer to the VM storage configuration https://github.com/DIMSI-IS/BackROLL?tab=readme-ov-file#backroll-configuration

**Comment by vigneshvrm** [comment]
Hi JoffreyLuang,

We have primary storage over a Fiber Channel connected to the KVM via a shared mount point, so it's technically not possible to mount the shared mount point in the VM. Does Backroll only support NFS mount points?

**Comment by JoffreyLuang** [comment]
Hi Vigneshvrm, 

At the moment, it supports only NFS. 
We're working on a storage agnostic solution but it is still in development.
